name: website

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install package dependencies
        run: npm ci && npx lerna bootstrap
      - run: npm test
      - name: Update Coverage Badge
        run: npm run update-badge
      - name: Generate documentation page
        run: |
          pip install json-schema-for-humans
          mkdir -p public/registry-schema
          generate-schema-doc registry.schema.json --config expand_buttons=true --config description_is_markdown=true public/registry-schema/index.html
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
